modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
[[mods]]
modId="controller-fix"
version="${file.jarVersion}"
displayName="Controller Fix"
description='''
This mod potentially fixes MinecraftForge/MinecraftForge#7285
'''
