modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
[[mods]]
modId="examplemod"
version="${file.jarVersion}"
displayName="Example Mod"
description='''
This mod [demonstrates|fixes] MinecraftForge/MinecraftForge#
'''
