modLoader="javafml"
loaderVersion="[35,)"
license="MIT / LGPL 2.1"
[[mods]]
modId="create-entity-on-load"
version="${file.jarVersion}"
displayName="Test Mod for Forge#7519"
description="Test Mod for Forge#7519"
